version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-development:
        dependency-type: development
      python-runtime:
        dependency-type: production

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/.packaging"
    schedule:
      interval: weekly

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
