title: HydroGym
description: A Platform for Reinforcement Learning Control in Fluid Dynamics
show_downloads: true
email: ludger.paehler@tum.de
github_username:  ludgerpaehler
theme: jekyll-theme-cayman
