[tool.poetry]
name = "hydrogym"
version = "0.1.2.1"
authors = [
    "Jared Callaham et al."
]
maintainers = [
    "Jared Callaham <jared.callaham@gmail.com>",
    "Ludger Paehler <ludger.paehler@tum.de>",
    "Sam Ahnert <sammahnert@gmail.com",
]
description = "A Reinforcement Learning Benchmarking Environment for Fluid Dynamics"
license = "MIT"
readme = "README.md"
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Physics",
]
documentation = "https://hydrogym.readthedocs.io/"
repository = "https://github.com/dynamicslab/hydrogym"
keywords = [
    "Reinforcement Learning",
    "Scientific Machine Learning",
    "Benchmarking",
    "Computational Fluid Dynamics"
]
include = [
    { path = "hydrogym"}
]

[tool.poetry.urls]
issues = "https://github.com/dynamicslab/hydrogym/issues"

[tool.poetry.dependencies]
control = "^0.9.2"
dmsuite = "^0.1.1"
evotorch = "^0.3.0"
gmsh = "^4.11.1"
gym = "^0.26.2"
modred = "^2.1.0"
python = "^3.8"
torch = "1.13"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.5.2"
ipykernel = "^6.19.4"
notebook = "^6.5.2"
ipywidgets = "^8.0.4"
mpltools = "^0.2.0"
nbformat = "^5.7.1"
nbconvert = "^7.2.7"
memory-profiler = "^0.61.0"
seaborn = "^0.12.1"
tensorboard = "^2.11.0"

# In case one seeks to add a further backend, their further dependencies need to be added to the 
# poetry dependencies above, as well as be specified here s.t. these additional dependencies
# can then later be installed with ```pip install hydrogym[sim_backend]```
[tool.poetry.extras]
#sim_backend = ["sim_framework"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
