#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# PettingZoo reproducible config for TCFmini_3D_Re180
# Intended to be used with prepare_workspace + mpirun from work_dir.

runner:
  # RL/interaction settings
  nb_interactions: 2500 # Number of interactions within one episode
  nb_episodes: 100
  nb_warmup_episodes: 1
  train_steps: 300 # Interval of training steps within one episode
  gradient_steps: 64 # Interval of gradient steps within one episode
  ckpt_int: 5 # Save checkpoint every 5 episodes
  RL_algorithm: "TD3"
  rescale_actions: true # Rescale actions to the range [-1, 1] then scale by u_tau
  learning_rate: 1e-3
  batch_size: 256 # Batch size for training
  buffer_size: 1000000 # Buffer size for experience replay
  learning_starts: 100
  tau: 0.005
  # --- For TD3 algorithm ---
  policy_delay: 2
  target_policy_noise: 0.0
  target_noise_clip: 0.0
  action_noise: 0.1 # 10% of the action space

  # Reproducibility and environment coupling
  seed: 1998
  random_init: 6
  rank: 1
  evaluation: false
  normalize_input: "utau"
  ctrl_min_amp: -0.06388353
  ctrl_max_amp: 0.06388353
  npl_state: 2
  u_tau: 0.06388353
  dUdy: 12.4271

simulation:
  CASENAME: "phill"
  solver_version: "v19"
  exeName: "nek5000"
  host: "localhost"
  hostfile: ""
  compile_path: "."
  restart_folder: "restart_files"

  # Core runtime configuration
  nproc: 10
  TOTCTRL: 220
  ndrl: 1
  znmf_avg: 0
  target_cfl: 2.0
  y_sensing: 15.0
  retau: 180.0 # Friction Reynolds number
  ys_bdf: 0.0 # Body-force method is not used in this case
  amp_bdf: 0.0 # Body-force method is not used in this case
  ret_bdf: 0.0 # Body-force method is not used in this case

  # SIZE (mesh)
  lx1: 6 # Polynomial order of GLL basis functions
  # -- Size of the domain --
  Lx: 2.67
  Ly: 1.0
  Lz: 0.8
  Nx: 4 # Number of spectral elements in the x-direction
  Ny: 16 # Number of spectral elements in the y-direction
  Nz: 4 # Number of spectral elements in the z-direction
  # -- Size of the actuator patch --
  nxs: 1
  nzs: 1

  # .par settings
  tmax: 100000.0
  stopAt: "numSteps"
  numSteps: 500000
  dt: -0.01 # Time step size (negative value means time step)
  timeStepper: "bdf3"
  variableDt: "no"
  writeControl: "timeStep"
  writeInterval: 100000
  dealiasing: "yes"
  filtering: "none"
  filterWeight: 0.01
  filterCutoffRatio: 0.9
  stressFormulation: "no"
  variableProperties: "no"
  p_residualTol: 1.0e-08
  p_residualProj: "no"
  v_residualTol: 1.0e-08
  v_residualProj: "no"
  density: 1.0
  viscosity: -2800 # Reb
  advection: "yes"

  # Runtime parameters
  PARFWRITE: "no"
  PARFNAME: "outparfile"
  LOGLEVEL: 1
  WALLTIME: "23:45"
  READCHKPT: "yes" # Read checkpoint file from the fully-developed flow field
  CHKPFNUMBER: 1
  # --- We are not using checkpointing in this case ---
  CHKPINTERVAL: 10000000
  AVSTEP: 10
  IOSTEP: 300000000
  # --- We are not using SMP in this case ---
  SMPSTEP: 23