name: Format

on: [push, pull_request]

jobs:
  yapf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff